name: Backend CI
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 20

          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install Dependencies
          run: npm install

        - name: Run Linting
          run: npm run lint

    create_test_folder_on_ec2:
        needs: lint
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v1

          - name: Create test folder on EC2 instance
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER}}
              key: ${{ secrets.EC2_SSH_KEY }}
              script: |
                cd ~/ && mkdir test

          

    unit_tests:
        needs: create_test_folder_on_ec2
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: SSH into EC2 and run unit tests
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  cd ~/test
                  npm install
                  npm run unit

            - name: Deploy to EC2 instance
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                ARGS: 
                  --exclude='.gitignore'
                  --exclude='.github/'
                  --exclude='README.md'
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                SOURCE: "./"
                REMOTE_HOST: ${{ secrets.EC2_HOST }}
                REMOTE_USER: ${{ secrets.EC2_USER }}
                TARGET: "~/test"

    integration_tests:
        needs: unit_tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: SSH into EC2 and run integration tests
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  cd ~/test
                  npm install
                  npm run integration

    clean_up_test_folder_on_ec2:
        needs: integration_tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: Remove test folder from EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  rm -r ~/test
