name: Backend CI
on:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true

            - name: Install clippy
              run: rustup component add clippy

            - name: Run clippy
              run: cargo clippy 

    deploy_to_ec2_test_folder:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout the code
            uses: actions/checkout@v1

          - name: Create test folder on EC2
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER}}
              key: ${{ secrets.EC2_SSH_KEY }}
              script: |
                cd ~/
                if [ -d "test" ]; then
                    sudo rm -rf ~/test
                fi
                mkdir ~/test

          - name: Deploy code to EC2 test folder
            uses: easingthemes/ssh-deploy@v2.1.5
            env:
                ARGS: 
                  --exclude='.gitignore'
                  --exclude='.github/'
                  --exclude='README.md'
                SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                SOURCE: "./"
                REMOTE_HOST: ${{ secrets.EC2_HOST }}
                REMOTE_USER: ${{ secrets.EC2_USER }}
                TARGET: "~/test"

    run_tests:
        needs: deploy_to_ec2_test_folder
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: SSH into EC2 and run tests
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  export PATH=$PATH:/home/admin/.cargo/bin
                  mkdir ~/test/db
                  cd ~/test/db
                  ./run_current_sql.sh
                  cd ..
                  sudo rm -rf target
                  sudo -E env "PATH=$PATH" cargo build
                  sudo -E env "PATH=$PATH" cargo test

    clean_up_test_folder_on_ec2:
        needs: run_tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: Remove test folder from EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER}}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  cd ~/
                  if [ -d "test" ]; then
                      sudo rm -rf ~/test
                  fi
